/**
 * Production-Ready Alerting System for Back4App
 * Implements comprehensive alerting and notification system
 * 
 * @author Shrikant Telang
 * @version 2.0.0
 */

const winston = require('winston');
const https = require('https');

// Configure logger
const logger = winston.createLogger({
  level: process.env.LOG_LEVEL || 'info',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.json()
  ),
  transports: [
    new winston.transports.Console(),
    new winston.transports.File({ filename: 'logs/alerts.log' })
  ]
});

// Alert configuration
const ALERT_CONFIG = {
  EMAIL_ENABLED: process.env.EMAIL_ALERTS_ENABLED === 'true',
  WEBHOOK_ENABLED: process.env.WEBHOOK_ALERTS_ENABLED === 'true',
  SLACK_ENABLED: process.env.SLACK_ALERTS_ENABLED === 'true',
  EMAIL_RECIPIENTS: process.env.ALERT_EMAIL_RECIPIENTS?.split(',') || [],
  WEBHOOK_URL: process.env.ALERT_WEBHOOK_URL,
  SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
  RATE_LIMIT_WINDOW: 5 * 60 * 1000, // 5 minutes
  MAX_ALERTS_PER_WINDOW: 10
};

// Alert storage
const alertHistory = new Map();
const rateLimitMap = new Map();

/**
 * Alert severity levels
 */
const SEVERITY_LEVELS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
};

/**
 * Alert types
 */
const ALERT_TYPES = {
  SYSTEM: 'system',
  SECURITY: 'security',
  PERFORMANCE: 'performance',
  BUSINESS: 'business',
  ERROR: 'error'
};

/**
 * Rate limiting for alerts
 */
function checkRateLimit(alertKey) {
  const now = Date.now();
  const windowStart = now - ALERT_CONFIG.RATE_LIMIT_WINDOW;
  
  if (!rateLimitMap.has(alertKey)) {
    rateLimitMap.set(alertKey, []);
  }
  
  const alerts = rateLimitMap.get(alertKey);
  const recentAlerts = alerts.filter(timestamp => timestamp > windowStart);
  
  if (recentAlerts.length >= ALERT_CONFIG.MAX_ALERTS_PER_WINDOW) {
    return false;
  }
  
  recentAlerts.push(now);
  rateLimitMap.set(alertKey, recentAlerts);
  return true;
}

/**
 * Create alert object
 */
function createAlert(type, severity, title, message, metadata = {}) {
  return {
    id: `alert_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    type,
    severity,
    title,
    message,
    metadata,
    timestamp: new Date().toISOString(),
    environment: process.env.NODE_ENV || 'development',
    service: 'cryptopulse-backend'
  };
}

/**
 * Send email alert
 */
async function sendEmailAlert(alert) {
  if (!ALERT_CONFIG.EMAIL_ENABLED || ALERT_CONFIG.EMAIL_RECIPIENTS.length === 0) {
    return;
  }
  
  try {
    const emailData = {
      to: ALERT_CONFIG.EMAIL_RECIPIENTS,
      subject: `[${alert.severity.toUpperCase()}] ${alert.title}`,
      html: `
        <h2>${alert.title}</h2>
        <p><strong>Severity:</strong> ${alert.severity.toUpperCase()}</p>
        <p><strong>Type:</strong> ${alert.type}</p>
        <p><strong>Time:</strong> ${alert.timestamp}</p>
        <p><strong>Message:</strong> ${alert.message}</p>
        ${alert.metadata ? `<p><strong>Metadata:</strong> <pre>${JSON.stringify(alert.metadata, null, 2)}</pre></p>` : ''}
        <hr>
        <p><em>This alert was generated by CryptoPulse Backend Monitoring System</em></p>
      `
    };
    
    // In production, this would use a real email service like SendGrid, AWS SES, etc.
    logger.info('Email alert sent', { alertId: alert.id, recipients: ALERT_CONFIG.EMAIL_RECIPIENTS });
    
  } catch (error) {
    logger.error('Failed to send email alert:', error);
  }
}

/**
 * Send webhook alert
 */
async function sendWebhookAlert(alert) {
  if (!ALERT_CONFIG.WEBHOOK_ENABLED || !ALERT_CONFIG.WEBHOOK_URL) {
    return;
  }
  
  try {
    const webhookData = {
      text: `🚨 *${alert.title}*`,
      attachments: [
        {
          color: getSeverityColor(alert.severity),
          fields: [
            { title: 'Severity', value: alert.severity.toUpperCase(), short: true },
            { title: 'Type', value: alert.type, short: true },
            { title: 'Time', value: alert.timestamp, short: true },
            { title: 'Message', value: alert.message, short: false }
          ],
          footer: 'CryptoPulse Backend Monitoring',
          ts: Math.floor(new Date(alert.timestamp).getTime() / 1000)
        }
      ]
    };
    
    await sendHttpRequest('POST', ALERT_CONFIG.WEBHOOK_URL, webhookData);
    logger.info('Webhook alert sent', { alertId: alert.id });
    
  } catch (error) {
    logger.error('Failed to send webhook alert:', error);
  }
}

/**
 * Send Slack alert
 */
async function sendSlackAlert(alert) {
  if (!ALERT_CONFIG.SLACK_ENABLED || !ALERT_CONFIG.SLACK_WEBHOOK_URL) {
    return;
  }
  
  try {
    const slackData = {
      text: `🚨 *${alert.title}*`,
      attachments: [
        {
          color: getSeverityColor(alert.severity),
          fields: [
            { title: 'Severity', value: alert.severity.toUpperCase(), short: true },
            { title: 'Type', value: alert.type, short: true },
            { title: 'Time', value: alert.timestamp, short: true },
            { title: 'Message', value: alert.message, short: false }
          ],
          footer: 'CryptoPulse Backend Monitoring',
          ts: Math.floor(new Date(alert.timestamp).getTime() / 1000)
        }
      ]
    };
    
    await sendHttpRequest('POST', ALERT_CONFIG.SLACK_WEBHOOK_URL, slackData);
    logger.info('Slack alert sent', { alertId: alert.id });
    
  } catch (error) {
    logger.error('Failed to send Slack alert:', error);
  }
}

/**
 * Get severity color for alerts
 */
function getSeverityColor(severity) {
  const colors = {
    [SEVERITY_LEVELS.LOW]: '#36a64f',      // Green
    [SEVERITY_LEVELS.MEDIUM]: '#ffaa00',   // Orange
    [SEVERITY_LEVELS.HIGH]: '#ff6600',     // Red-Orange
    [SEVERITY_LEVELS.CRITICAL]: '#ff0000'  // Red
  };
  return colors[severity] || '#808080';
}

/**
 * Send HTTP request
 */
function sendHttpRequest(method, url, data) {
  return new Promise((resolve, reject) => {
    const options = {
      method,
      headers: {
        'Content-Type': 'application/json'
      }
    };
    
    const req = https.request(url, options, (res) => {
      let responseData = '';
      res.on('data', chunk => responseData += chunk);
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          resolve(responseData);
        } else {
          reject(new Error(`HTTP ${res.statusCode}: ${responseData}`));
        }
      });
    });
    
    req.on('error', reject);
    req.setTimeout(10000, () => {
      req.destroy();
      reject(new Error('Request timeout'));
    });
    
    if (data) {
      req.write(JSON.stringify(data));
    }
    req.end();
  });
}

/**
 * Send alert
 */
async function sendAlert(type, severity, title, message, metadata = {}) {
  const alert = createAlert(type, severity, title, message, metadata);
  
  // Check rate limiting
  const rateLimitKey = `${type}_${severity}`;
  if (!checkRateLimit(rateLimitKey)) {
    logger.warn('Alert rate limited', { alertId: alert.id, type, severity });
    return;
  }
  
  // Store alert
  alertHistory.set(alert.id, alert);
  
  // Log alert
  logger.warn('Alert triggered', alert);
  
  // Send alerts in parallel
  const alertPromises = [
    sendEmailAlert(alert),
    sendWebhookAlert(alert),
    sendSlackAlert(alert)
  ];
  
  try {
    await Promise.allSettled(alertPromises);
  } catch (error) {
    logger.error('Failed to send some alerts:', error);
  }
  
  return alert;
}

/**
 * System alerts
 */
async function alertSystemDown(service, error) {
  return sendAlert(
    ALERT_TYPES.SYSTEM,
    SEVERITY_LEVELS.CRITICAL,
    `System Down: ${service}`,
    `Service ${service} is down: ${error.message}`,
    { service, error: error.message }
  );
}

async function alertSystemDegraded(service, details) {
  return sendAlert(
    ALERT_TYPES.SYSTEM,
    SEVERITY_LEVELS.HIGH,
    `System Degraded: ${service}`,
    `Service ${service} is experiencing issues: ${details}`,
    { service, details }
  );
}

/**
 * Security alerts
 */
async function alertSecurityBreach(type, details) {
  return sendAlert(
    ALERT_TYPES.SECURITY,
    SEVERITY_LEVELS.CRITICAL,
    `Security Breach: ${type}`,
    `Security incident detected: ${details}`,
    { type, details }
  );
}

async function alertSuspiciousActivity(activity, details) {
  return sendAlert(
    ALERT_TYPES.SECURITY,
    SEVERITY_LEVELS.HIGH,
    `Suspicious Activity: ${activity}`,
    `Suspicious activity detected: ${details}`,
    { activity, details }
  );
}

/**
 * Performance alerts
 */
async function alertHighLatency(service, latency) {
  return sendAlert(
    ALERT_TYPES.PERFORMANCE,
    SEVERITY_LEVELS.MEDIUM,
    `High Latency: ${service}`,
    `Service ${service} has high latency: ${latency}ms`,
    { service, latency }
  );
}

async function alertHighErrorRate(service, errorRate) {
  return sendAlert(
    ALERT_TYPES.PERFORMANCE,
    SEVERITY_LEVELS.HIGH,
    `High Error Rate: ${service}`,
    `Service ${service} has high error rate: ${errorRate}%`,
    { service, errorRate }
  );
}

/**
 * Business alerts
 */
async function alertTradingAnomaly(anomaly, details) {
  return sendAlert(
    ALERT_TYPES.BUSINESS,
    SEVERITY_LEVELS.HIGH,
    `Trading Anomaly: ${anomaly}`,
    `Trading anomaly detected: ${details}`,
    { anomaly, details }
  );
}

async function alertRiskThresholdExceeded(threshold, value) {
  return sendAlert(
    ALERT_TYPES.BUSINESS,
    SEVERITY_LEVELS.MEDIUM,
    `Risk Threshold Exceeded`,
    `Risk threshold ${threshold} exceeded: ${value}`,
    { threshold, value }
  );
}

/**
 * Error alerts
 */
async function alertCriticalError(error, context) {
  return sendAlert(
    ALERT_TYPES.ERROR,
    SEVERITY_LEVELS.CRITICAL,
    `Critical Error`,
    `Critical error occurred: ${error.message}`,
    { error: error.message, stack: error.stack, context }
  );
}

/**
 * Get alert history
 */
function getAlertHistory(limit = 100) {
  const alerts = Array.from(alertHistory.values())
    .sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp))
    .slice(0, limit);
  
  return alerts;
}

/**
 * Get alert statistics
 */
function getAlertStatistics() {
  const alerts = Array.from(alertHistory.values());
  const stats = {
    total: alerts.length,
    bySeverity: {},
    byType: {},
    last24Hours: 0,
    lastHour: 0
  };
  
  const now = new Date();
  const last24Hours = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const lastHour = new Date(now.getTime() - 60 * 60 * 1000);
  
  alerts.forEach(alert => {
    // Count by severity
    stats.bySeverity[alert.severity] = (stats.bySeverity[alert.severity] || 0) + 1;
    
    // Count by type
    stats.byType[alert.type] = (stats.byType[alert.type] || 0) + 1;
    
    // Count recent alerts
    const alertTime = new Date(alert.timestamp);
    if (alertTime > last24Hours) {
      stats.last24Hours++;
    }
    if (alertTime > lastHour) {
      stats.lastHour++;
    }
  });
  
  return stats;
}

module.exports = {
  sendAlert,
  alertSystemDown,
  alertSystemDegraded,
  alertSecurityBreach,
  alertSuspiciousActivity,
  alertHighLatency,
  alertHighErrorRate,
  alertTradingAnomaly,
  alertRiskThresholdExceeded,
  alertCriticalError,
  getAlertHistory,
  getAlertStatistics,
  SEVERITY_LEVELS,
  ALERT_TYPES
};
